project:
  type: website
  output-dir: docs

website:
  title: "Ariana S. Huffmyer, PhD"
  site-url: "https://ahuffmyer.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Lab Notebook"
        href: notebook.qmd
      - text: "Gallery"
        href: gallery.qmd
    right:
      - icon: github
        href: https://github.com/AHuffmyer
      - icon: bluesky
        href: https://bsky.app/profile/cnidariana.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/ariana-s-huffmyer/
  
  page-footer:
    left: "Â© 2026 Ariana Huffmyer"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3

execute:
  freeze: auto
